version: '3.4'

services:
  controlecerto:
    image: ${DOCKER_REGISTRY-}controlecerto
    build:
      context: .
      dockerfile: ControleCerto.Api/Dockerfile
    ports:
        - "8080:8080"
        - "8081:8081"
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=12345
    ports:
      - "5672:5672"
      - "15672:15672"
  cache:
    image: redis:7.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

networks:
  default:
    driver: bridge


