# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  finantech:
    build:
      context: "/home/guiduarte/RiderProjects/Finantech_backend"
      dockerfile: "Finantech.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "finantech:dev"
    ports:
    - "127.0.0.1:57000:57100"
    - "127.0.0.1:57200:57300"
    volumes:
    - "/home/guiduarte/.nuget/packages:/home/app/.nuget/packages"
    - "/home/guiduarte/RiderProjects/Finantech_backend/Finantech.Api:/app:rw"
    - "/home/guiduarte/RiderProjects/Finantech_backend:/src:rw"
    - "/home/guiduarte/.local/share/JetBrains/RiderRemoteDebugger/2024.1.4/Linux64:/opt/rider-debugger"
    - "/home/guiduarte/Programs/JetBrains.Rider/bin:/etc/opt/rider-debugger/backend-log.xml"
    - "/home/guiduarte/.cache/JetBrains/Rider2024.1/log/DebuggerWorker/JetBrains.Debugger.Worker.2024_8_16_10_38_15:/var/opt/rider-debugger:rw"
    working_dir: "/app"
