# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  finantech:
    build:
      context: "/home/guiduarte/RiderProjects/Finantech_backend"
      dockerfile: "Finantech.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Finantech.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "finantech:dev"
    ports: []
    volumes:
    - "/home/guiduarte/.nuget/packages:/home/app/.nuget/packages"
    - "/home/guiduarte/RiderProjects/Finantech_backend/Finantech.Api:/app:rw"
    - "/home/guiduarte/RiderProjects/Finantech_backend:/src:rw"
    working_dir: "/app"
